---
- hosts: all
  become: yes
  tasks:
  - name: "Install Git"
    yum:
      name: git
      state: present
  - name: "Download docker script"
    command: curl -fsSL get.docker.com -o get-docker.sh
    args:
      chdir: /home/ansible/
  - name: "run docker script"
    script: get-docker.sh
  - name: "start Docker"
    service: 
      name: docker
      state: started
  - name: "install pip"
    yum:
      name: python-pip
      state: present
  - name: "install docker-compose"
    command: pip install docker-compose
  - name: "clone git repo"
    command: git clone <<url>>
    args:
      chdir: /home/ansible/
  - name: "unzip the file"
    unarchive:
    src: https://example.com/example.zip
    dest: /home/ansible/example
    remote_src: yes
  - name: "run docker-compose build"
    command: docker-compose build 
    args:
      chdir: /home/ansible/example/
  - name: "run docker-compose up"
    command: docker-compose up
    args:
      chdir: /home/ansible/example/
  - name: "run docker-compose start"
    command: docker-compose start
    args:
      chdir: /home/ansible/example/    
